Rise-Vision/widget-video

- README.md
- circle.yml
- package.json
- test/integration/storage-v1/messaging-file.html
- test/integration/storage-v2/messaging-file.html
- Fixed incorrect source paths for a couple integration tests
- Forcing CCI to use latest Node version 6.9.1
- PhantomJS requires being a global package when used in Node 6.x.x, adding it as a pre install for CCI
> Fix integration tests and apply latest Node and PhantomJS

- src/widget/css/video.css
- src/widget/player-vjs.js
- test/integration/non-storage/file.html
- test/unit/widget/player-vjs-spec.js
Changed css rule to use !important.
Removed the loadingSpinner from the videojs.options.children array. That will make it to not load the spinner component at all.
Fixed tests
@donnapep @stulees please review. cheers
Presentation here: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=81b77624-9a58-43d6-9538-b497a0cdbf85?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
> Removed loadingSpinner

- bower.json
- src/widget/storage-file.js
- src/widget/storage-folder.js
- test/integration/js/file.js
- test/integration/js/folder.js
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/js/messaging-file.js
- test/integration/js/messaging-folder.js
- Updating to use latest release of rise-storage v2 
- Conditionally populating `error_details` value in handler of `rise-storage` "rise cache not running" event based on `e.detail` object props
- Showing message "Waiting for Rise Cache" if `isPlayerRunning` present and `true` in handler of `rise-storage` "rise cache not running" event
- Added integration tests for file and folder scenarios
> Handling "rise-cache-not-running" event to show message when running in player

- src/widget/non-storage.js
- src/widget/storage-file.js
- src/widget/storage-folder.js
- test/integration/js/file.js
- test/integration/js/messaging-file.js
- test/integration/js/messaging-folder.js
`isV2Running` takes a callback function as a parameter. The function call was missing this callback.
Also, if RC v2 was running, `statusCode` was 0, which would result in no error message showing on the Display. `statusCode` is now set regardless of which version of Rise Cache is running.
Fixes #179.
> Fix call to isV2Running

- bower.json
- package.json
- src/widget/player-vjs.js
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/non-storage/logging.html
- test/unit/widget/player-vjs-spec.js
Updated tests
@donnapep @stulees I have talked to @alanclayton and we think that inverting the use of the fluid option will be a valid solution for us. So when scaling to fit option is true, fluid is going to be false. 
This is presentation showing a comparison with JWPlayer and also how it looks when the placeholder has the same size as the video. http://rva.risevision.com/#/PRESENTATION_MANAGE/id=9e4329da-8bb1-4c91-a531-97d62c71309a?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
Please review. cheers
@tejohnso @settinghead FYI.
> Fixed scale to fit issue by reverting the use of fluid option [stage-4]

- bower.json
- The changes in 1.4.2 release of `rise-storage` component have not been fully validated, reverting to avoid issues
> Revert rise-storage v2 version [stage-2]

- src/widget/player-vjs.js
The video is currently pausing at the last frame, causing a flash when the play is called again.
Also the current behaviour is not consistent on Windows and Linux, remainingTime was returning slightly different values.
@Rise-Vision/content @stulees please review
> Resetting no matter where the video currently is

- bower.json
- test/integration/non-storage/file.html
An integration test regarding non-storage file had to be removed. It passed consistently locally but failed consistently on CCI, even with some adjustments. It appears to be a timing issue. It is not a test that is critical to this Widget.
> Upgrade rise-storage for appending display id to url when RC not running

- bower.json
- package.json
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/non-storage/logging.html
- Same as Image, plan is to bump version so we can eventually change Editor to start using new version and only impact new presentations while we monitor reliability and issues. Once stable, we will revert version back. 
- Also helps to initiate smaller incremental changes for PR reviews. 
@andrecardoso @santiagonoguez @tejohnso FYI
> Bump version for RLS work [stage-2]

- src/widget/player-local-storage-file.js
- src/widget/player-vjs.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- src/widget/video.js
- test/integration/js/player-local-storage-logging-file.js
- When logging in RLS single file scenario, ensuring `file_url` field value is the GCS file path so that the `file_format` field is auto configured correctly (based on file extension)
- When logging in RLS single file scenario, now additionally adding `local_url` field and applying value of local file url (when possible).
@andrecardoso @santiagonoguez @tejohnso FYI
> Revise logging to adhere to RLS single file

- package-lock.json
- package.json
- src/widget/player-local-storage-file.js
- src/widget/player-vjs.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- src/widget/video.js
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-messaging-file.js
- test/integration/non-storage/file.html
@jungeunyoon FYI the fix for 217 that was deployed broke the widget when configured for RLS single file. I've fixed/refactored it in this PR also, cheers.
> Prevent repetitive logging of file error from other widget instances

- src/widget/player-local-storage-file.js
- test/integration/js/player-local-storage-logging-file.js
- Widget should not have reliability impacted by a display being unauthorized for Storage
> Downgrade "unauthorized" to a warning event [stage-2]

- package-lock.json
- package.json
@Rise-Vision/content please review - growl v1.10.2 didn't fix the vulnerability issue so this updates to v1.10.5. Thanks!
> updates growl to 1.10.5 to fix known vulnerability

- gulpfile.js
- package-lock.json
- package.json
- src/widget.html
- src/widget/main.js
- src/widget/player-local-storage-file.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- test/integration/player-local-storage/file.html
- test/integration/player-local-storage/logging-file.html
- test/integration/player-local-storage/messaging-file.html
- Adds instantiation of common licensing library
- Compares company id provided by gadgets rpc call with the company id provided in the widget settings data that is associated with the storage file (or folder) and provides to the licensing instantiation. 
- If company ids are the same, licensing module will be used for authorization
- Licensing common library handles making direct request to Store API if company ids are different and the company id associated with file is not white listed. 
- Widget logs if there is an authorization failure when a direct request has been made
> Support getting Storage licensing authorization without Licensing module

- circle.yml
- `cp` was not overwriting files on GCS
- `rsync` with `-d` will also remove files that are not present in latest push
> Fix the remote push of files to GCS with rsync command [stage-2]

- src/widget/video-rls.js
- src/widget/video.js
This will help in reviewing logs as it will ensure "configuration" event is logged prior to any other events (ie. error).
> Log configuration event prior to sending "ready" to Viewer [stage-2]

- src/widget/video-utils.js
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/non-storage/logging.html
- test/unit/widget/video-utils-spec.js
- We need to differentiate "error" logs by configuration, this allows us to do so
- `video_v2_events` table has had a _configuration_ field added
> Add logging value for new "configuration" field [stage-2]

- src/widget/player-local-storage-folder.js
- test/integration/js/player-local-storage-logging-folder.js
- During initialization, if 1 file available without needing processing (already cached), delays for 2 seconds to allow more files, then widget initializes with however many files it has
- No opportunity for integration test in this scenario, requires a restart
> Fix one file in folder issue [stage-2]

- src/widget/video-utils.js
- test/unit/widget/video-utils-spec.js
- Fixes issue #240 
- Presentation validated on my display YSD5WEDW339F - https://apps.risevision.com/editor/workspace/dce2352c-c43f-4bf0-a219-6e2c94f9d3f1/?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
> Fix getStorageFileName() util function to account for # or ? in file name

- bower.json
- src/widget/player-local-storage-file.js
- src/widget/player-local-storage-folder.js
- src/widget/player-vjs.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- test/integration/js/player-local-storage-file.js
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/js/player-local-storage-messaging-file.js
- test/integration/js/player-local-storage-messaging-folder.js
- Disposing of VideoJS player when file deleted in single file configuration. 
- Disposing of VideoJS player when all files in a folder are unable to be played
- all files were deleted
- all files in folder are resulting in player error
- Accounting for no `dispose` event triggered due to using `5.11.1` version of VideoJS. Setting a delay to account for removing of DOM and other cleanup. 
- After disposing player instance, re-applying necessary `<video>` element back into container `<div>` in HTML 
- Forcing to use `3.1.1` of video-js-playlist plugin as they've introduced a breaking change by dropping Bower support. `3.1.1` is the last version used in production Video widget. 
Validated with staged version of Widget in Player for all scenarios.
> Do not show video when file(s) have been deleted

- src/widget/player-local-storage-folder.js
- src/widget/video-rls.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/js/player-local-storage-messaging-folder.js
- In either situation of folder doesn't exist or folder is empty, behaviour now is to continue to log to BQ but immediately notify Viewer `done` and do not display anything on screen. 
- Downgrading folder doesn't exist scenario to a warning, it shouldn't impact our reliability as it is a user controlled scenario. 
- Fix for issue https://github.com/Rise-Vision/rise-launcher-electron/issues/773
> Stop displaying error for folder NOEXIST and EMPTYFOLDER messages

- src/widget/player-vjs.js
- Retry playing the video when a MEDIA_DECODE error occurs, every 1 second, max 5 attempts
- Listening for `play` videojs event to reset the decode retry count
- Fix for issue #256
> Retry playing video after MEDIA_DECODE error

- src/widget/player-vjs.js
The `fileCount` value used in player-vjs.js is getting out of sync with the current playlist. It is not exactly known why but it looks to be the reason behind the defect https://github.com/Rise-Vision/chrome-os-player/issues/184 .
To avoid this, the more reliable approach instead of using the `fileCount` counter is to obtain what the current index of the playlist is in order to compare to the length of the list, which can be done via playlist api `playlist.currentItem()`. This will ensure an accurate current index value.
> Rely on vjs playlist api for current index of playlist item being played

- src/widget/storage-file.js
- src/widget/storage-folder.js
Ensuring `event_details` value has a true value in a couple specific endpoint logs
Making sure all endpoint logs successfully get inserted
With presentation https://apps.risevision.com/editor/workspace/c65d35db-dca8-4c33-9976-2096c3eddfc8?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f and running in preview (where invalid endpoint logs were caught via console) using Charles to map to locally built version of Widget. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
> Fix event_details value for a couple endpoint logs

- package-lock.json
- package.json
Use `v1.18.0` of common-component
PR #282 was pointing to latest commit version and not a release tag
Staged version of widget
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
> Use latest release of common-component

- src/widget/player-local-storage-file.js
- src/widget/player-local-storage-folder.js
- src/widget/rise-content-sentinel-file.js
- src/widget/rise-content-sentinel-folder.js
- test/index.html
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/js/rise-content-sentinel-file.js
- test/integration/js/rise-content-sentinel-folder.js
- test/integration/js/rise-content-sentinel-logging-file.js
- test/integration/js/rise-content-sentinel-logging-folder.js
- test/integration/rise-content-sentinel/logging-file.html
- test/integration/rise-content-sentinel/logging-folder.html
Using new `E000000215` code for a file error when using content sentinel and continuing to use `E000000027` specifically for RLS
Also now ensuring to check if file error message is associated with "insufficient disk space" and if so logging with error code `E000000040`. 
Including the `watchType` as additional debug info
Logs are indicating `E000000027` is being reported from endpoints where RLS would not be running therefore adding confusion to investigation and what is defined in Error Definitions for `E000000027`
Staged version of widget in this presentation https://apps.risevision.com/editor/workspace/d6ad8a54-16b9-4ae8-a04e-1ddfbb058a4a?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f 
Tested shared schedules with stage-2 of Viewer (support video widget)
Tested Player
- As the Submitter, …
> Differentiate file error code for RLS and Content Sentinel

- package-lock.json
- package.json
- Use latest common-component v1.18.1
The latest common-component uses `cachePath` instead of `filePath` parameter which fixes issue https://github.com/Rise-Vision/content-sentinel/issues/124
Tested on viewer-stage-1 and used proxy to load local version of the widget-video.
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
> Use latest common-component

- bower.json
Prevent the flow of processing sending logs to client-side-events project by using latest widget-common. See https://github.com/Rise-Vision/common-template/pull/203 for changes. 
https://github.com/Rise-Vision/widget-common/issues/168
Tested using Charles Proxy to map to local version of common-template and config-prod and ran a schedule on ChrOS player. Validated no logs to `Display_Events.events` were inserted. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been …
> Prevent processing logs to client-side-events

- bower.json
- package-lock.json
Use latest widget-common, see https://github.com/Rise-Vision/widget-common/pull/173 for changes to support using Content Sentinel if running in `webplayer`
Issue #226 
Validated with staged version of widget in presentation in a schedule for Electron display and confirmed with https://widgets.risevision.com/viewer/?type=webplayer&id=3G6G6C78J4NF
Also validated still working as expected in legacy preview, shared schedule, and display. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/36003 …
> Use content sentinel for type 'webplayer'
