- .gitignore
- circle.yml
- dist/player.html
- src/player.html
@donnapep I have updated the jwplayer key, please review. cheers
> Updated key

- bower.json
- circle.yml
- dist/components/rise-storage/rise-storage.html
[stage-3]
@stulees please review. cheers
> Change to version where there is not get fallback

- bower.json
- circle.yml
- dist/components/rise-storage/rise-storage.html
Reverts Rise-Vision/widget-video#63
@stulees reverting this as it will break current CAP. I merged by mistake but I didn't let the build run so it was not deployed. We are safe I mean. cheers
> Revert "Change to version where there is not get fallback"

- dist/settings.html
- src/settings.html
@donnapep @stulees @rodrigopavezi I added a css selector to main container div. I am going to target this selector in full story so anytime someone clicks in the settings it starts recording.
> added css selector to target in fullstory

- bower.json
- dist/components/polymer/polymer-micro.html
- dist/components/polymer/polymer-mini.html
- dist/components/polymer/polymer.html
- dist/components/rise-storage/rise-storage.html
@donnapep @stulees please review. cheers
> Upgraded rise component to fix cors error message

- bower.json
- dist/components/rise-storage/rise-storage.html
@donnapep @stulees please review.
Presentation here: 
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=a14df7d6-b196-49cd-b533-423be1afedf7?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
> Updated rise storage component to fix problem with storage api error

- gulpfile.js
- Adding "bower-update" gulp task which will run a `bower update`
- Added "bower-update" task to the "build" task as a preliminary task
> Update bower on gulp "build" task [stage-2]

- bower.json
- dist/components/rise-storage/rise-storage.html
@stulees please review. cheers
> Updated version of the storage component

- bower.json
- dist/components/rise-storage/rise-storage.html
@donnapep @stulees please review. cheers
Presentation here:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=2988d6fe-6647-46c5-9a7b-9ab3da8e8dcf?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
> Upgraded storage component

- bower.json
- gulpfile.js
Fix config for 'test' value
[stage-1]
> Update rise-storage version

- src/widget/main.js
- src/widget/storage-file.js
- src/widget/storage-folder.js
- src/widget/video.js
- test/integration/js/file.js
- test/integration/js/folder.js
- test/integration/non-storage/file.html
- test/integration/non-storage/logging.html
- test/integration/non-storage/messaging-legacy-player.html
- test/integration/non-storage/messaging.html
- test/integration/non-storage/pre-merge.html
- test/integration/storage-v1/file.html
- test/integration/storage-v1/folder.html
- test/integration/storage-v1/logging-file.html
- test/integration/storage-v1/logging-folder.html
- test/integration/storage-v1/messaging-file.html
- test/integration/storage-v1/messaging-folder.html
- test/integration/storage-v2/file.html
- test/integration/storage-v2/folder.html
- test/integration/storage-v2/logging-file.html
- test/integration/storage-v2/logging-folder.html
- test/integration/storage-v2/messaging-file.html
- test/integration/storage-v2/messaging-folder.html
- Applying display id value to `rise-storage` attribute `displayid`
- Revised and added integration test coverage
> Applying displayid value to rise-storage attribute

- src/widget/player-utils.js
- src/widget/player-vjs.js
- test/unit/widget/player-utils-spec.js
- Listening for "loadedMetaData" videojs player event and logging placeholder and video dimensions and aspect ratios as well as scale to fit selection
> Log "aspect" event providing dimensions and aspect ratio

- src/widget/non-storage.js
- src/widget/video.js
- test/integration/non-storage/messaging.html
- When unavailable flag is set and widget is told to play, now it retries RC for the file
- Integration test added
> Retry RC for 3rd party file [stage-2]

- bower.json
- circle.yml
- src/widget/main.js
- test/integration/js/version.js
- test/integration/storage-v2/file.html
- test/integration/storage-v2/folder.html
- test/integration/storage-v2/logging-file.html
- test/integration/storage-v2/logging-folder.html
- test/integration/storage-v2/messaging-file.html
- test/integration/storage-v2/messaging-folder.html
Updated tests
Using the new function for checking if RC v2 is running or if it is a player with it even though it is not running so it will load SC v2. 
@donnapep @stulees please review. cheers.
presentation here http://rvashow2.appspot.com/Viewer.html?type=display&player=true&id=7DJ3WFU5G545&claimId=&sysInfo=os%3D64-bit%20Ubuntu%2014.04.4%20LTS%0A%26pn%3DRisePlayerElectron%26iv%3D2016.11.17.19.50%26jv%3D%26pv%3D2016.11.17.19.50%26ev%3D1.2.0%26ip%3D10.0.2.15
> Changed the widget to check for RC V2 using new function from commons

- bower.json
@stulees @tejohnso please review. cheers
> Updated rise storage to check RC version before double encode

- bower.json
@tejohnso @stulees please review. cheers
> Updated rise storage v2 to fix loop

- circle.yml
- package.json
- src/widget.html
- Deploying to `widgets.risevision.com` bucket on GCS
- Setting domain of document to "risevision.com"
> Stage & Deploy to GCS

- src/widget/player-vjs.js
This reverts commit 08abc4435c953ecdca9eb4b70357354ca504ef5c.
@sheadarlison fyi
> Revert "Resetting no matter where the video currently is"

- src/widget/player-vjs.js
Reapplying that fix with some extra call to `load` and a way to detect and log the issue if it reappears.
The extra call to `load` improved a lot the situation on Chrome 59 and the timer prevent the videos from hanging forever on the loading/pending state.
@Rise-Vision/content @stulees please review
> Resetting no matter where the video currently is

- src/widget.html
- src/widget/main.js
- src/widget/video-rls.js
- src/widget/video.js
- First of many PRs towards video using RLS for single file (work already done on Image widget)
- Configured to execute new logic/code if widget is configured for storage single file
- Removed previous background testing
@andrecardoso @santiagonoguez @tejohnso FYI
> Determine to use RLS for single file

- package-lock.json
- package.json
- src/widget/player-local-storage-file.js
- test/integration/js/player-local-storage-logging-file.js
@Rise-Vision/content @Rise-Vision/delivery FYI
> Fix problematic licensing retries [stage-2]

- src/widget/main.js
- Changes are a part of [staggered release design](https://docs.google.com/document/d/1ZNFs_garsh9NlncqIB-WfRzgTTnyEDv5XI1nXhgeUsA/edit)
- single file vs folder using RLS can stagger release separately 
@andrecardoso @santiagonoguez @tejohnso FYI
> Implement staggered release by leveraging top window flags [stage-2]

- package-lock.json
- package.json
@jungeunyoon @stulees please review - this updates the security vulnerabilities in the hoek and uglify-js dependencies. 
Thanks!
> updates dependency security vulnerabilities

- package-lock.json
- package.json
@jungeunyoon @Rise-Vision/content please review - updates the growl dependency to 1.10.2 to fix vulnerability. Thanks!
> updates growl to fix know vulnerability

- bower.json
- gulpfile.js
- src/settings.html
> Use latest file-selector component to fix translations [stage-4]

- src/settings.html
Updates JQuery reference
Complements previous change, reference in settings.html still points to old JQuery version.
Manually tested using staged video settings here:
https://apps.risevision.com/editor/workspace/85f87511-911d-4dd4-91f8-83e0101cc0ea?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
And the runtime component was tested also in preview and in player using this schedule:
https://apps.risevision.com/schedules/details/79f1b75f-93e4-4918-9df3-8f25dca40696?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013
- To be released before Friday, or on Monday
- No new automated tests are needed. 
- Release plan, to be …
> update jquery in settings.html

- .circleci/config.yml
- bower.json
- package-lock.json
- package.json
- src/widget/main.js
- src/widget/non-storage.js
- src/widget/player-local-storage-file.js
- src/widget/player-local-storage-folder.js
- src/widget/player-vjs.js
- src/widget/storage-file.js
- src/widget/storage-folder.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- src/widget/video.js
- test/integration/js/file.js
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/non-storage/logging.html
Use latest widget-common to facilitate endpoint logging / heartbeats
Widget changes include:
- Executing starting heartbeat
- Updated execution of `configuration` event log to ensure endpoint logging
- Now ensuring a `version` file is created and the value is used for logging. 
- Updated execution of `error` event logs to include endpoint logging (with error codes)
- CCI config updated to use latest required image
Updated `video_v2_events` table schema (and existing tables) to add `env`, `viewer_id`, and `version` fields. 
Added errorCode to error log calls for correct endpoint logging format. Updated [error log spreadsheet](https://docs.google.com/spreadsheets/d/1DcuiuAFWohadKKmCBZp_rAnj5J0kUTBN-g9_jj9kXNw/edit#gid=0)
Endpoint logging / heartbeats
Tested with a staged version of widget …
> Enable endpoint logging / heartbeats

- package-lock.json
- src/widget/non-storage.js
- src/widget/player-local-storage-file.js
- src/widget/player-local-storage-folder.js
- src/widget/player-vjs.js
- src/widget/storage-file.js
- src/widget/storage-folder.js
- src/widget/video-rls.js
- src/widget/video-utils.js
- src/widget/video.js
- test/integration/js/logging-file.js
- test/integration/js/logging-folder.js
- test/integration/js/player-local-storage-logging-file.js
- test/integration/js/player-local-storage-logging-folder.js
- test/integration/non-storage/logging.html
Update error codes as per approved corrections
Ensure to provide debug info where applicable
Improving non-storage error logging applying a specific error code depending on Rise Cache response status
Fix issue #279  by now logging an error code specific to a media error code/name
Uptime standards
Tested with staged widget in player 
https://apps.risevision.com/editor/workspace/8d696f62-2f6e-4018-abf1-2800e3b6af72?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release …
> Update error codes

- src/widget/video.js
Added uptime error for HTTP-based File URL.
This is a part of the ongoing epic implementation.
Unit tests.
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
> Added uptime error for HTTP-based File URL
